version: '3.4'

services:
    abn-recipe-api:
        container_name: abn-recipe-api
        image : recipe-api:latest
        build: .
        ports:
            - "8080:8081"
            - "8090:8090"
        networks:
          recipe-api-network:
            ipv4_address: 10.20.0.12
        
networks:
  recipe-api-network:
    ipam:
      driver: default
      config:
        - subnet: 10.20.0.0/24
        